export interface Course {
  // can represent a user-created course or a canvas course.
  id: string; // needs an ID generated by us, and an id generated by Canvas, .
  userId: string;
  instructor?: string;
  name: string;
  term?: string; // can be an enum, will introduct later.
}

export interface CanvasCourse extends Course {
  canvasCourseId: string; //nullable? i dont think it is
  canvasCode: string;
  isImported: boolean;
}
